name: SpatialModal
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.1
  - bokeh=3.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - cffi=1.17.1
  - comm=0.2.2
  - contourpy=1.3.1
  - curl=8.11.1
  - cytoolz=1.0.1
  - dask=2024.12.1
  - dask-core=2024.12.1
  - dask-expr=1.1.21
  - debugpy=1.8.14
  - decorator=5.2.1
  - executing=2.2.0
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gflags=2.2.2
  - gfortran_impl_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=4.3.0
  - heapdict=1.0.1
  - icu=73.1
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - msgpack-python=1.0.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openblas=0.3.28
  - openjpeg=2.5.2
  - openssl=3.5.0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.50.7
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.44.2
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-lmdb=1.6.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - r-base=4.3.1
  - r-mclust=6.1.1
  - re2=2022.04.01
  - readline=8.2
  - rpy2=3.5.11
  - s2n=1.3.27
  - setuptools=75.1.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - tktable=2.10
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - allensdk==2.16.2
      - anndata==0.11.1
      - argschema==3.0.4
      - array-api-compat==1.9.1
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - blosc2==2.7.1
      - boto3==1.35.84
      - botocore==1.31.17
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - cycler==0.12.1
      - dask-image==2024.5.3
      - datashader==0.17.0
      - distributed==2025.2.0
      - distro==1.9.0
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fasteners==0.19
      - filelock==3.16.1
      - fonttools==4.55.1
      - frozenlist==1.5.0
      - fsspec==2023.6.0
      - future==1.0.0
      - geopandas==1.0.1
      - glymur==0.13.6
      - gprofiler-official==1.0.0
      - greenlet==3.1.1
      - gseapy==1.1.6
      - h5py==3.12.1
      - harmonypy==0.0.10
      - hdmf==3.14.5
      - idna==3.10
      - igraph==0.11.8
      - imageio==2.36.1
      - importlib-metadata==8.6.1
      - inflect==7.5.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - llvmlite==0.44.0
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - marshmallow==3.23.2
      - matplotlib==3.9.3
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpl-chord-diagram==0.4.1
      - mpld3==0.5.10
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - narwhals==1.33.0
      - natsort==8.4.0
      - ndindex==1.9.2
      - ndx-events==0.2.0
      - networkx==3.4.2
      - numba==0.61.0
      - numcodecs==0.13.1
      - numexpr==2.10.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ome-zarr==0.10.3
      - omnipath==1.0.8
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - param==2.2.0
      - patsy==1.0.1
      - pims==0.7
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pooch==1.8.2
      - pot==0.9.5
      - propcache==0.2.1
      - psutil==6.1.0
      - psycopg2-binary==2.9.10
      - py-cpuinfo==9.0.0
      - pyct==0.5.0
      - pynndescent==0.5.13
      - pynrrd==1.1.1
      - pynwb==2.8.3
      - pyogrio==0.10.0
      - pyproj==3.7.1
      - python-igraph==0.11.8
      - referencing==0.35.1
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - s3fs==2023.6.0
      - s3transfer==0.10.4
      - scanpy==1.10.4
      - scikit-build==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scikit-misc==0.5.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - semver==3.0.2
      - session-info==1.0.0
      - shapely==2.0.7
      - simpleitk==2.4.0
      - simplejson==3.19.3
      - slicerator==1.1.0
      - spatial-image==1.1.0
      - spatialdata==0.2.5.post0
      - sqlalchemy==2.0.36
      - squidpy==1.6.2
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - sympy==1.13.1
      - tables==3.10.1
      - tblib==3.0.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tomli==2.2.1
      - torch==2.5.1
      - torch-geometric==2.6.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - typeguard==4.4.2
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==1.26.20
      - validators==0.34.0
      - wot==1.0.8.post2
      - wrapt==1.17.2
      - xarray==2024.7.0
      - xarray-dataclasses==1.9.1
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.18.3
      - zarr==2.18.3
